Update weread.yml

diff --git a/.github/workflows/weread.yml b/.github/workflows/weread.yml
--- a/.github/workflows/weread.yml
+++ b/.github/workflows/weread.yml
@@ -55,5 +55,6 @@ jobs:
             echo "No changes to commit."
           else
             git commit -m 'Sync changes between Notion and WeRead'
-            git push || echo "Failed to push changes."
+            git pull origin main
+            git push origin main || echo "Failed to push changes."
           fi
