Update weread.yml

diff --git a/.github/workflows/weread.yml b/.github/workflows/weread.yml
--- a/.github/workflows/weread.yml
+++ b/.github/workflows/weread.yml
@@ -4,26 +4,14 @@ on:
   workflow_dispatch:
   schedule:
     - cron: "0 0 * * *"
+
 jobs:
   sync:
     name: Sync
     runs-on: ubuntu-latest
     env:
-      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
-      NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
-      WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
-      BOOK_DATABASE_NAME: ${{ vars.BOOK_DATABASE_NAME }}
-      AUTHOR_DATABASE_NAME: ${{ vars.AUTHOR_DATABASE_NAME }}
-      CATEGORY_DATABASE_NAME: ${{ vars.CATEGORY_DATABASE_NAME }}
-      BOOKMARK_DATABASE_NAME: ${{ vars.BOOKMARK_DATABASE_NAME }}
-      REVIEW_DATABASE_NAME: ${{ vars.REVIEW_DATABASE_NAME }}
-      CHAPTER_DATABASE_NAME: ${{ vars.CHAPTER_DATABASE_NAME }}
-      YEAR_DATABASE_NAME: ${{ vars.YEAR_DATABASE_NAME }}
-      WEEK_DATABASE_NAME: ${{ vars.WEEK_DATABASE_NAME }}
-      MONTH_DATABASE_NAME: ${{ vars.MONTH_DATABASE_NAME }}
-      DAY_DATABASE_NAME: ${{ vars.DAY_DATABASE_NAME }}
-      REF: ${{ github.ref }}
-      REPOSITORY: ${{ github.repository }}
+      # ... (your existing environment variables)
+
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -32,18 +20,26 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: 3.11
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
+
       - name: weread sync
         run: |
           python -u scripts/weread.py
-      - name: push
+
+      - name: Commit and Push Changes
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add .
-          git commit -m 'add new cover' || echo "nothing to commit"
-          git pull
-          git push || echo "nothing to push"
+
+          # Check if there are changes to commit
+          if git diff --cached --exit-code; then
+            echo "No changes to commit."
+          else
+            git commit -m 'Sync changes between Notion and WeRead'
+            git push || echo "Failed to push changes."
+          fi
